const categoryHierarchy = {
  "Personal Protective Equipment (PPE) & Safety Gear": {
    "Face Masks & Respirators": [
      "Surgical Masks",
      "N95 Respirators",
      "Dust Masks",
      "Face Shields",
      "Reusable Face Masks",
      "Anti - Fog Masks",
      "Respirator Cartridges & Filters",
    ],
    "Gloves & Hand Protection": [
      "Disposable Gloves",
      "Cut - Resistant Gloves",
      "Heat - Resistant Gloves",
      "Rubber Gloves",
      "Leather Work Gloves",
      "Medical Examination Gloves",
      "Finger Guards",
    ],
    "Eye Protection": [
      "Safety Glasses",
      "Welding Goggles",
      "Impact - Resistant Goggles",
      "Face Shields",
      "Prescription Safety Glasses",
      "Laser Protection Glasses",
      "Anti - Scratch & Anti - Fog Lenses",
    ],
    "Hearing Protection": [
      "Foam Earplugs, Silicone Earplugs",
      "Noise - Cancelling Headphones",
      "Earmuff Hearing Protectors",
      "Digital Hearing Protection",
      "Disposable Earplugs",
      "Custom - Molded Earplugs",
    ],
    "High-Visibility Clothing": [
      "Reflective Vests",
      "Hi - Vis Jackets & Coats",
      "Hi - Vis Pants & Bibs",
      "Reflective Gloves",
      "Traffic Safety Clothing",
      "Neon Safety Hats",
      "Work Wear with Reflective Tape",
    ],
    "Protective Clothing": [
      "Disposable Coveralls",
      "Chemical - Resistant Coveralls",
      "Flame - Resistant Coveralls",
      "Chemical - Resistant Aprons",
      "Welding Protective Clothing",
      "High - Visibility Coveralls",
      "Lab Coats & Gowns",
      "Protective Sleeves & Bibs",
    ],
    "Work Boots & Footwear": [
      "Steel-Toe Boots",
      "Waterproof Work Boots",
      "Slip - Resistant Boots",
      "Insulated Boots",
      "Hiking Boots for Work",
      "Safety Shoes",
      "Composite Toe Footwear",
    ],
  },
  "Industrial Tools & Machinery": {
    "Power Tools": [
      "Cordless Drills, Impact Drivers",
      "Angle Grinders",
      "Circular Saws",
      "Reciprocating Saws",
      "Jigsaws",
      "Sanders",
      "Heat Guns",
      "Power Tool Combo Kits",
    ],
    "Hand Tools": [
      "Adjustable Wrenches",
      "Hammers",
      "Screwdrivers",
      "Pliers",
      "Measuring Tapes",
      "Utility Knives",
      "Sockets & Socket Sets",
    ],
    "Cutting Tools": [
      "Cutting Torches",
      "Band Saws",
      "CNC Milling Machines",
      "Hole Saw Kits",
      "Hacksaws",
      "Scissors & Shears",
      "Metal Cutters ",
    ],
    "Lifting & Rigging Equipment": [
      "Hoists",
      "Chain Slings & Shackles",
      "Lifting Straps",
      "Winches",
      "Overhead Cranes",
      "Forklifts & Pallet Jacks",
      "Pulley Systems ",
    ],
    "Welding & Soldering Tools": [
      "MIG Welders, TIG Welders",
      "Welding Torches & Accessories",
      "Soldering Irons",
      "Welding Helmets & Masks",
      "Plasma Cutters",
      "Welding Rods & Electrodes ",
    ],
    "Fastening Tools": [
      "Pneumatic Nail Guns, Staple Guns",
      "Rivet Guns",
      "Screw Guns",
      "Torque Wrenches",
      "Pneumatic Fasteners",
      "Power Staplers ",
    ],
    "Heavy Machinery": [
      "Mini Excavators",
      "Bulldozers",
      "Skid Steer Loaders",
      "Backhoe Loaders",
      "Track Loaders",
      "Cranes",
      "Excavator Attachments ",
    ],
  },
  "Electrical Instruments & Appliances ": {
    "Circuit Breakers & Fuses": [
      "Miniature Circuit Breakers, Molded Case Circuit Breakers",
      "Fuse Holders & Bases",
      "Cartridge Fuses",
      "Thermal Circuit Breakers",
      "Resettable Fuses",
      "Surge Protection Devices ",
    ],
    "Cable & Wiring": [
      "Electrical Cables, Extension Cords",
      "Coaxial Cables",
      "Ethernet Cables",
      "Power Cords & Plugs",
      "PVC Insulated Wires",
      "Armored Cables ",
    ],
    "Electrical Testers & Meters": [
      "Multimeters, Clamp Meters",
      "Circuit Testers",
      "Voltage Detectors",
      "Insulation Resistance Testers",
      "Power Analyzers",
      "Earth Ground Resistance Meters ",
    ],
    "Switches & Sockets": [
      "Light Switches, Dimmer Switches",
      "Electrical Outlets",
      "GFCI Outlets",
      "Smart Switches",
      "Push Button Switches",
      "USB Wall Outlets",
      "Electrical Outlet Boxes ",
    ],
    "Lighting Fixtures & Bulbs": [
      "LED Bulbs, Incandescent Bulbs",
      "Fluorescent Lights",
      "Pendant Lighting",
      "Recessed Lighting",
      "Emergency & Exit Lighting",
      "Floodlights & Spotlights",
      "Lamp Fixtures & Bases ",
    ],
    "Power Strips & Extension Cords": [
      "Surge Protector Power Strips, Heavy - Duty Extension Cords",
      "Wall - Mountable Power Strips",
      "Multi - Outlets",
      "Cordless Power Strips",
      "Power Cords for Appliances",
      "Extension Cord Reels ",
    ],
    "Electric Motors & Transformers": [
      "Induction Motors, Synchronous Motors",
      "Step - Up / Step - Down Transformers",
      "Brushless Motors",
      "Electric Actuators",
      "DC Motors",
      "Servo Motors",
      "Motor Controllers ",
    ],
  },
  "Home Appliances": {
    "Kitchen Appliances": [
      "Refrigerators & Freezers",
      "Microwaves & Ovens",
      "Coffee Makers & Espresso Machines",
      "Blenders & Food Processors",
      "Dishwashers",
      "Cooktops & Ranges",
      "Rice Cookers & Slow Cookers",
    ],
    "Laundry Appliances": ["Washing Machines", "Dryers", "Irons & Steamers"],
    "Heating & Cooling Appliances": [
      "Air Conditioners",
      "Heaters",
      "Fans",
      "Air Purifiers & Humidifiers",
    ],
    "Home Comfort & Appliances": [
      "Vacuum Cleaners",
      "Water Heaters",
      "Air Fryers & Deep Fryers",
      "Dehumidifiers & Humidifiers",
    ],
  },
  Gadgets: {
    "Smart Home Devices": [
      "Smart Speakers & Assistants",
      "Smart Lights & Bulbs",
      "Smart Plugs & Switches",
      "Security Cameras & Systems",
      "Smart Thermostats",
      "Smart Appliances",
    ],
    "Wearable Technology": [
      "Smartwatches & Fitness Trackers",
      "Wireless Earbuds & Headphones",
      "Smart Glasses & VR Headsets",
    ],
    "Mobile Devices & Accessories": [
      "Smartphones & Tablets",
      "Phone Cases & Screen Protectors",
      "Mobile Charging Devices",
    ],
    "Personal Gadgets": [
      "Drones & UAVs",
      "Smart Cameras & Photography Gear",
      "Portable Speakers & Bluetooth Devices",
    ],
    "Health & Wellness Gadgets": [
      "Air Purifiers & Humidifiers",
      "Fitness Gadgets & Accessories",
      "Massage Devices",
    ],
  },
  "Medical, Laboratory & Hospital Equipment": {
    "Diagnostic Tools": [
      "Digital Thermometers",
      "Infrared Thermometers",
      "Stethoscopes",
      "Blood Pressure Monitors",
      "Pulse Oximeters",
      "Glucometers",
    ],
    "Medical Instruments": [
      "Surgical Scalpels",
      "Hemostats & Forceps",
      "Needles & Sutures",
      "Scissors & Dissecting Tools",
      "Clamps & Retractors",
      "Bone Chisels & Mallets",
    ],
    "Patient Monitoring Equipment": [
      "ECG Machines",
      "Blood Oxygen Monitors",
      "Thermometers",
      "Vital Sign Monitors",
      "Infusion Pumps",
      "Bedside Monitors",
    ],
    "Lab Glassware & Consumables": [
      "Beakers & Flasks",
      "Petri Dishes",
      "Test Tubes & Racks",
      "Pipettes",
      "Lab Funnels & Filters",
      "Centrifuge Tubes",
    ],
    "Lab Consumables": [
      "Sterilization Equipment",
      "Autoclaves",
      "UV Sterilizing Cabinets",
      "Steam Sterilizers",
      "Disinfectants & Cleaners",
    ],
    "Surgical Instruments": [
      "Scalpels & Blades",
      "Surgical Forceps & Clamps",
      "Surgical Scissors",
      "Suture Kits",
      "Sponges",
      "Drapes & Gowns",
    ],
    "Hospital Furniture": [
      "Electric & ICU Beds",
      "Examination Chairs",
      "Patient Recliners",
      "Stretchers",
      "Overbed Tables",
      "Medical Carts & Trolleys",
    ],
  },
  "Office Supplies & Stationery": {
    Paper: [
      "Copy Paper",
      "Graphing Paper",
      "Notebooks & Journals",
      "Cardstock & Specialty Paper",
      "Construction Paper",
      "Paper Rolls",
      "Envelopes",
    ],
    "Writing Instruments": [
      "Ballpoint Pens",
      "Gel Pens",
      "Mechanical Pencils",
      "Highlighters",
      "Markers",
      "Fountain Pens",
      "Crayons & Colored Pencils",
    ],
    "Desk Organizers & Storage": [
      "Desk Trays",
      "File Holders",
      "Drawer Organizers",
      "Document Racks",
      "Pen Holders",
      "Letter Sorters",
      "Shelving Units",
    ],
    "Filing & Document Management": [
      "Filing Cabinets",
      "Hanging File Folders",
      "File Boxes",
      "Document Binders",
      "Labels & Label Makers",
      "Paper Clips & Staples",
      "Archive Boxes",
    ],
    "Office Furniture": [
      "Ergonomic Office Chairs",
      "Standing Desks",
      "Office Workstations",
      "Filing Cabinets & Desks",
      "Conference Tables",
      "Bookshelves",
      "Task Lighting",
    ],
    "Calendars & Planners": [
      "Wall Calendars",
      "Desk Planners",
      "Weekly & Monthly Planners",
      "Appointment Books",
      "Day Planners",
      "Pocket Calendars",
      "Digital Planners",
    ],
    "Office Technology": [
      "Laser Printers",
      "Inkjet Printers",
      "3D Printers",
      "All-in-One Printers",
      "Scanners",
      "Fax Machines",
      "Paper Shredders",
    ],
  },
  "Automotive Parts & Accessories": {
    "Car Batteries & Electrical Components": [
      "Lead-Acid & Lithium-Ion Car Batteries",
      "Alternators",
      "Starters & Solenoids",
      "Battery Chargers & Jump Starters",
      "Fuse Boxes & Relays",
      "Battery Terminals & Cables",
    ],
    "Tires & Wheels": [
      "All-Season, Winter & Off-Road Tires",
      "Performance Tires",
      "Alloy & Steel Wheels",
      "Tire Pressure Monitors",
    ],
    "Brake Parts & Suspension": [
      "Brake Pads & Shoes",
      "Brake Rotors & Drums",
      "Brake Calipers & Cylinders",
      "Shock Absorbers & Struts",
      "Suspension Springs & Bushings",
      "Brake Fluid & Hydraulic Components",
    ],
    "Engine & Transmission Components": [
      "Timing Belts & Chains",
      "Pistons & Piston Rings",
      "Engine Blocks & Heads",
      "Transmission Fluid",
      "Clutch Kits & Parts",
      "Oil & Air Filters",
      "Radiators & Cooling Fans",
    ],
    "Interior Accessories": [
      "Custom Seat Covers",
      "Floor Mats",
      "Steering Wheel Covers",
      "Car Organizers",
      "Dashboard Covers",
      "Car Upholstery",
      "Sunshades & Window Films",
    ],
    "Exterior Accessories": [
      "Roof Racks & Cargo Carriers",
      "Tow Bars & Hitches",
      "Car Covers & Sunshades",
      "Side Steps & Running Boards",
      "Mud Flaps & Splash Guards",
      "Window Deflectors",
      "Car Mirrors & Lights",
    ],
    "Tools for Automotive Repair & Maintenance": [
      "Automotive Diagnostic Tools",
      "Wrenches & Ratchets",
      "Torque Wrenches",
      "Car Jacks & Lifts",
      "Air Compressors & Pneumatic Tools",
      "Oil Change Tools",
      "Car Cleaning Tools",
    ],
  },
  "Construction & Building Materials": {
    "Cement, Concrete & Mortar": [
      "Portland Cement",
      "Ready-Mix Concrete",
      "Mortar Mix",
      "Concrete Admixtures",
      "Quick-Set Cement",
      "Formwork & Sealers",
    ],
    "Lumber & Wood Products": [
      "Softwood & Hardwood Lumber",
      "Plywood & MDF",
      "Wood Planks & Panels",
      "Pressure-Treated Lumber",
      "Timber Beams & Posts",
    ],
    "Steel, Metal & Rebar": [
      "Steel Beams & Columns",
      "Rebar",
      "Galvanized Steel Sheets",
      "Metal Roofing & Cladding",
      "Stainless Steel Sheets & Bars",
    ],
    "Insulation Materials": [
      "Fiberglass Insulation",
      "Spray Foam Insulation",
      "Rigid Foam Board",
      "Reflective & Acoustic Insulation",
      "Insulated Panels & Boards",
    ],
    "Roofing & Siding": [
      "Asphalt Shingles",
      "Metal Roofing Sheets",
      "Roof Underlayment & Felt",
      "Vinyl & Fiber Cement Siding",
      "Cedar Wood Shingles",
      "Roof Flashing & Ventilation",
    ],
    Flooring: [
      "Ceramic & Porcelain Tiles",
      "Hardwood, Laminate & Vinyl Plank Flooring",
      "Carpets & Rugs",
      "Stone Flooring",
      "Carpet Underlayments",
    ],
    "Paint & Coatings": [
      "Interior & Exterior Paint",
      "Primers & Sealers",
      "Waterproof & Epoxy Coatings",
      "Spray Paint",
      "Wood Stains & Finishes",
      "Anti-Corrosion Paint",
    ],
  },
  "Farming & Agricultural Tools": {
    "Tractors & Agricultural Machinery": [
      "Compact Tractors",
      "Plows & Harrows",
      "Combine Harvesters",
      "Rotary Tillers",
      "Seeders & Planters",
      "Hay Balers",
      "Mowers & Brush Cutters",
    ],
    "Irrigation Systems": [
      "Drip Irrigation Kits",
      "Sprinkler Systems",
      "Water Pumps",
      "Irrigation Hoses & Pipes",
      "Soaker Hoses",
      "Irrigation Controllers",
      "Flood Irrigation Systems",
    ],
    "Seeds & Fertilizers": [
      "Vegetable, Flower & Turf Seeds",
      "Organic & Synthetic Fertilizers",
      "Soil Amendments",
      "Compost & Mulch",
    ],
    "Livestock Equipment": [
      "Cattle Feeders & Waterers",
      "Chicken Coops & Nesting Boxes",
      "Horse Stalls & Fencing",
      "Livestock Scales",
      "Milking Machines",
      "Veterinary Tools",
      "Livestock Tags",
    ],
    "Crop Protection": [
      "Insecticides & Pesticides",
      "Herbicides & Fungicides",
      "Weed Control",
      "Rodenticides",
      "Organic Crop Protection",
      "Crop Protection Sprayers",
    ],
    "Hand Tools": [
      "Shovels, Rakes & Hoes",
      "Pruning Shears & Loppers",
      "Trowels & Spades",
      "Weeders & Cultivators",
      "Hedge Trimmers",
      "Garden Forks",
    ],
    "Soil & Field Testing Equipment": [
      "Soil Test Kits",
      "pH & Moisture Meters",
      "Soil Temperature Gauges",
      "Conductivity Meters",
      "Compaction Testers",
      "Field Test Kits",
    ],
  },
  "Packaging Solutions & Material Handling Equipment": {
    "Packaging Materials": [
      "Corrugated Boxes",
      "Bubble Wrap & Packing Peanuts",
      "Stretch Film & Shrink Wrap",
      "Poly Bags & Mailers",
      "Packing Tape & Dispensers",
      "Foam Inserts",
      "Wrapping Paper",
    ],
    "Stretch Film & Shrink Wrap": [
      "Hand & Machine Stretch Film",
      "Shrink Wrap Rolls & Bags",
      "Stretch Film Dispensers",
      "Shrink Wrap Heat Guns",
      "Pallet Wrap",
    ],
    "Pallets & Crates": [
      "Wooden & Plastic Pallets",
      "Stackable Crates & Pallets",
      "Bulk Storage Bins",
      "Plastic Crates & Totes",
    ],
    "Conveyors & Belt Systems": [
      "Roller, Belt & Powered Conveyors",
      "Chain & Flexible Conveyors",
      "Conveyor Belts",
      "Overhead Conveyors",
    ],
    "Forklifts & Pallet Jacks": [
      "Electric Forklifts",
      "Manual Pallet Jacks",
      "Stackers & Lifting Trucks",
      "Forklift Attachments",
      "Pallet Trucks",
    ],
    "Labeling & Marking Systems": [
      "Barcode Printers & Scanners",
      "Labeling & Handheld Printers",
      "Thermal & Inkjet Printers",
      "RFID Tags & Printers",
    ],
    "Packaging Tape & Dispensers": [
      "Clear & Duct Tape",
      "Packing Tape Dispensers",
      "Double-Sided & Waterproof Tape",
      "Stretch & Fragile Tape",
    ],
  },
  "Food & Beverage Products": {
    Beverages: [
      "Carbonated Soft Drinks",
      "Energy Drinks",
      "Fruit Juices",
      "Bottled Water",
      "Beer & Wine",
      "Coffee & Tea",
      "Sports Drinks",
    ],
    "Snacks & Confectioneries": [
      "Chips & Pretzels",
      "Cookies & Crackers",
      "Candy & Chocolates",
      "Nuts & Dried Fruits",
      "Snack Bars",
      "Popcorn",
      "Granola & Trail Mix",
    ],
    "Dairy Products": [
      "Milk & Cream",
      "Cheese",
      "Yogurt & Kefir",
      "Butter & Margarine",
      "Ice Cream & Frozen Desserts",
      "Whey Protein",
      "Dairy-Free Alternatives",
    ],
    "Meat & Seafood": [
      "Fresh Meat",
      "Processed Meats",
      "Frozen Seafood",
      "Fresh Fish",
      "Canned Meats & Seafood",
      "Game Meat",
      "Meat Substitutes",
    ],
    "Fresh Produce": [
      "Fresh Fruits",
      "Fresh Vegetables",
      "Organic Produce",
      "Herbs & Spices",
      "Citrus Fruits",
      "Exotic Fruits",
      "Root Vegetables",
    ],
    "Frozen Foods": [
      "Frozen Meals",
      "Frozen Vegetables & Fruits",
      "Frozen Meat & Fish",
      "Frozen Pizzas & Snacks",
      "Frozen Desserts & Ice Cream",
      "Frozen Breakfast Foods",
    ],
    "Canned & Packaged Goods": [
      "Canned Vegetables & Fruits",
      "Canned Soups & Stews",
      "Canned Beans & Legumes",
      "Canned Meats & Fish",
      "Ready Meals",
      "Pasta & Noodles",
      "Canned Juices",
    ],
    "Spices & Seasonings": [
      "Black Pepper",
      "Salt",
      "Cumin",
      "Turmeric",
      "Paprika",
      "Garlic Powder",
    ],
    "Cooking Oils": ["Olive Oil", "Vegetable Oil", "Coconut Oil"],
    "Vinegar & Sauces": [
      "Balsamic Vinegar",
      "Soy Sauce",
      "Hot Sauce",
      "BBQ Sauce",
    ],
    "Grains & Rice": ["Basmati Rice", "Brown Rice", "Quinoa", "Oats"],
    "Flours & Baking Ingredients": [
      "All-Purpose Flour",
      "Almond Flour",
      "Yeast",
      "Baking Powder",
    ],
    "Sugars & Sweeteners": ["White Sugar", "Brown Sugar", "Honey", "Stevia"],
    "Canned & Jarred Goods": ["Pickles", "Olives", "Sauerkraut"],
    "Pasta & Noodles": ["Spaghetti", "Macaroni", "Udon", "Rice Noodles"],
    "Condiments & Dressings": [
      "Ketchup",
      "Mustard",
      "Mayonnaise",
      "Salad Dressings",
    ],
  },
  "Apparel & Fashion Items": {
    "Men's Clothing": [
      "T-Shirts",
      "Jeans & Trousers",
      "Jackets & Blazers",
      "Sweaters & Hoodies",
      "Shorts & Cargo Pants",
      "Suits",
      "Sportswear",
    ],
    "Women's Clothing": [
      "Dresses & Gowns",
      "Tops & Blouses",
      "Skirts & Pants",
      "Sweaters & Cardigans",
      "Outerwear",
      "Activewear",
      "Maternity Clothing",
    ],
    Footwear: [
      "Casual Shoes",
      "Work Boots",
      "Sandals & Flip-Flops",
      "Dress Shoes & Heels",
      "Running Shoes",
      "Sports Shoes",
      "Winter Boots",
    ],
    Accessories: [
      "Belts",
      "Hats & Caps",
      "Scarves & Gloves",
      "Jewelry",
      "Sunglasses",
      "Watches",
      "Bags & Wallets",
    ],
    "Sportswear & Activewear": [
      "Running Gear",
      "Yoga Pants",
      "Athletic Jackets",
      "Sports Bras",
      "Gym Shoes",
      "Sports Socks",
      "Swimwear",
    ],
    Outerwear: [
      "Winter Coats",
      "Raincoats",
      "Bomber Jackets",
      "Leather Jackets",
      "Puffer Jackets",
      "Wool Coats",
      "Ski Jackets",
    ],
    "Kids' Clothing & Babywear": [
      "Baby Onesies",
      "Kids’ T-Shirts",
      "Toddler Shoes",
      "Baby Hats",
      "Baby Blankets",
      "Baby Jackets",
      "Boys' & Girls' Outerwear",
    ],
  },
};

module.exports = categoryHierarchy;
